[package]
name = "benchmarks_gungraun"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra.workspace = true
num-traits.workspace = true
my_linalg.path = "../my_linalg"

[dev-dependencies]
gungraun = "0.17.0"

[[bench]]
name = "vector_add"
harness = false
